# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bigMVP <- function(Y, X, prior_var, max_it, epsilon, m) {
    .Call(`_bigMVP_bigMVP`, Y, X, prior_var, max_it, epsilon, m)
}

bigMVP_lkj <- function(Y, X, prior_var, max_it, epsilon, m, nu_lkj) {
    .Call(`_bigMVP_bigMVP_lkj`, Y, X, prior_var, max_it, epsilon, m, nu_lkj)
}

bigMVPh <- function(Y, X, eta0, nu0, gamma0, Lambda0, eta0_rho, nu0_rho, gamma0_rho, lambda0_sq_rho, max_it, epsilon, m, nmcmc, burnin) {
    .Call(`_bigMVP_bigMVPh`, Y, X, eta0, nu0, gamma0, Lambda0, eta0_rho, nu0_rho, gamma0_rho, lambda0_sq_rho, max_it, epsilon, m, nmcmc, burnin)
}

rcpparma_hello_world <- function() {
    .Call(`_bigMVP_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_bigMVP_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_bigMVP_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_bigMVP_rcpparma_bothproducts`, x)
}

